default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: szymon
  password: Szymon/123
  host: localhost

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  <<: *default
  database: produdtion